### ISSUE TITLE
Limit `/test` invocations to Vector members with write access

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector-test-harness-github-actions-test-repo#7]
Calling `/test` in a comment should be limited to users who have write access to the Vector repo. This is somewhat important since someone with nefarious intentions could repeatedly call this to run up a cost.

**Comment by MOZGIII** [comment]
This should already be covered:
https://github.com/timberio/vector-test-harness-github-actions-test-repo/blob/1f63286423f1c11dd5055b5ad97bbc155cf3e0f6/.github/workflows/test-harness.yml#L31-L36

**Comment by binarylogic** [comment]
👍
